version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: web
    volumes:
      - ./:/app
      - /app/node_modules

    # command: npm run dev -- --inspect
    ports:
      - 3000:3000