version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.services.web.loadbalancer.server.port=3000"  # Port exposed by the frontend service
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - traefik
