version: "3"

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    container_name: web
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  go-app:
    build:
      context: ./backend/test_executor
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    container_name: go-app-container

  go-app-settings:
    build:
      context: ./backend/settings
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    container_name: go-app-container-settings