# Use the official GoLang image as the base image
FROM golang:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the local source code to the container's working directory
COPY . .

# Copy the configuration file into the container
COPY config.json .

# Download and install any dependencies
RUN go mod download

# Build the Go application
RUN go build -o server

# Expose the port that the application will run on
EXPOSE 8080

# Command to run the application when the container starts
CMD ["./server"]
