// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddTestInput struct {
	Status    string `json:"status"`
	Startedby string `json:"startedby"`
}

type AddUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

