# Use the official GoLang image as the base image
FROM golang:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the local source code to the container's working directory
COPY . .
COPY go.mod go.sum ./
ENV GOPATH /app

# Download and install any dependencies
RUN go mod download

# Build the Go application
RUN go build -o server

# Expose the port that the application will run on
EXPOSE 8080
ENV PORT 8181 # TODO check if needed
EXPOSE 8181 # TODO check if needed

# Command to run the application when the container starts
CMD ["./server"]
