version: "3"

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: api-gateway
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      -  3000:3000