package routes

import (
	"cicd_runner/config"
	"cicd_runner/db"
	"cicd_runner/models"
	"cicd_runner/utils"
	"fmt"
	"log"
	"net/http"
	"strconv"
	"time"

	"github.com/gin-gonic/gin"
)

/*
	type LastCommit struct {
		ID        string `json:"id"`        // SHA of commit
		Message   string `json:"message"`   // Commit message
		Timestamp string `json:"timestamp"` // ISO8601
	}
*/
type PushEventPayload struct {
	//	HeadCommit LastCommit `json:"head_commit"`
	Repository struct {
		FullName string `json:"full_name"`
	} `json:"repository"`
}

func CommitCallback(c *gin.Context) {
	var requestBody PushEventPayload

	err := c.ShouldBindJSON(&requestBody)
	if err != nil {
		log.Println("Error binding JSON", err)
		return
	}

	//Retreive the useful information from the database

	pipelineId, err := db.GetPipelineIdByRepositoryPath(requestBody.Repository.FullName)
	if err != nil {
		log.Println("Error getting pipeline ID", err)
		return
	}

	pipelineName, err := db.GetPipelineNameByPipelineId(pipelineId)
	if err != nil {
		log.Println("Error getting pipeline name", err)
		return
	}

	//Retrieve the access token for the pipeline
	AccessToken, err := db.GetAccessTokenByPipelineId(pipelineId)
	if err != nil {
		log.Fatalf("Error getting access token: %s", err.Error())
		return
	}

	//Retreive the UserId for the pipeline
	UserId, err := db.GetUserIdByPipelineId(pipelineId)
	if err != nil {
		log.Fatalf("Error getting user ID: %s", err.Error())
		return
	}

	//Retrieve the API Key for the UserId
	APIKey, err := db.GetAPIKeyByUserId(UserId)
	if err != nil {
		log.Fatalf("Error getting API key: %s", err.Error())
		return
	}

	//Creating the pipeline event/////////////////////////////////////////////////////////
	pipelineEvent := models.PipelineEvent{
		PipelineID: pipelineId,
		Status:     "running",
		Timestamp:  time.Now(),
		Duration:   0,
		Details:    fmt.Sprintf("Commit to the %s branch", requestBody.Repository.FullName),
		Type:       "test",
	}

	//The event id will be automatically generated by the database
	err = db.CreatePipelineEvent(&pipelineEvent)
	if err != nil {
		log.Println("Error creating pipeline event", err)
		return
	}

	//Send the pipeline event to the frontend
	err = utils.SendPipelineEvent(pipelineEvent)
	if err != nil {
		log.Fatalf("Error sending pipeline event: %s", err.Error())
		return
	}
	////////////////////////////////////////////////////////////////////////////////////////

	//Execute the test cases///////////////////////////////////////////////////////////////

	//Step 1: Pull the test cases from the repository///////////////////////////////////////
	err = utils.PullTestCases(requestBody.Repository.FullName, AccessToken)
	if err != nil {
		log.Fatalf("Error pulling test cases: %s", err.Error())
		return
	}

	//Step 2: First get the test id from the reverse proxy///////////////////////////////////////
	req, err := http.NewRequest("POST", fmt.Sprintf("%s/thex/test", config.EnvConfig.ReverseProxyUrl), nil)
	if err != nil {
		log.Fatalf("Failed to request TestId from THex: %s", err.Error())
		return
	}
	req.Header.Add("thex-key", APIKey)
	req.Header.Add("thex-proj", pipelineName)
	req.Header.Add("thex-pipeline-event-id", strconv.FormatUint(uint64(pipelineEvent.ID), 10))
	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		log.Fatalf("Failed to request TestId from THex: %s", err.Error())
		return
	}
	testId := resp.Header.Get("thex-test")
	if testId == "" {
		log.Fatalf("THex refused to send TestId")
		return
	}
	resp.Body.Close()
	log.Printf("Received TestId: %s", testId)

	//Step 3: Setup the parameters for the reverse proxy///////////////////////////////////////
	config.ProxyConfig.SetValues(APIKey, pipelineName, testId)

	log.Println("ProxyConfig values set successfully")
	apiKey, pipelineName, testId := config.ProxyConfig.GetValues()
	log.Printf("TestId: %s", testId)
	log.Printf("APIKey: %s", apiKey)
	log.Printf("PipelineName: %s", pipelineName)

	//Step 4: Execute the test cases///////////////////////////////////////////////////////////////
	err = utils.ExecuteTestCases()
	if err != nil {
		log.Fatalf("Error executing test cases: %s", err.Error())
		return
	}

	//Step5. Delete the test cases////////////////////////////////////////////////////////////
	err = utils.DeleteTestCases()
	if err != nil {
		log.Println("Error deleting test cases", err)
		return
	}

	//Step 6. End the test_Session
	req, err = http.NewRequest("DELETE", fmt.Sprintf("%s/thex/test", config.EnvConfig.ReverseProxyUrl), nil)
	if err != nil {
		log.Fatalf("Failed to create DELETE request: %s", err.Error())
		return
	}
	req.Header.Add("thex-key", APIKey)
	req.Header.Add("thex-proj", pipelineName)
	req.Header.Add("thex-test", testId)
	resp, err = client.Do(req)
	if err != nil {
		log.Fatalf("Failed to end test session: %s", err.Error())
		return
	}
	resp.Body.Close()
	log.Printf("Test session closed")

	//Step 7: Update the pipeline event status///////////////////////////////////////////////////////////////
	pipelineEvent.Status = "success"
	pipelineEvent.Duration = time.Since(pipelineEvent.Timestamp).Nanoseconds()
	pipelineEvent.Timestamp = time.Now()
	pipelineEvent.Details = "Test cases executed successfully"
	pipelineEvent.Type = "test"

	//Update the pipeline event in the database//////////////////
	err = db.UpdatePipelineEvent(&pipelineEvent)
	if err != nil {
		log.Fatalf("Error updating pipeline event: %s", err.Error())
		return
	}

	//Send the pipeline event to the frontend////////////////////
	err = utils.SendPipelineEvent(pipelineEvent)
	if err != nil {
		log.Fatalf("Error sending pipeline event: %s", err.Error())
		return
	}

	log.Printf("Pipeline event sent to frontend: %s", resp.Status)
}
