name: AM Service CI

on:
  push:
    branches:
      - main
    paths:
      - ./hub/am
      - .github/workflows/am-service.yml

  pull_request:
    branches:
      - main
    paths:
      - ./hub/am
      - .github/workflows/am-service.yml

jobs:
  buildnpush:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image (AM)
      run: docker build ./hub/am --tag jawadc/thex:am-latest

    - name: Push Docker image (AM)
      run: docker push jawadc/thex:am-latest