name: deployment

on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows:
      - ProxySE Service CI
      - FE Service CI
      - AM Service CI
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Copy SSH PEM file from secrets
      run: echo ${{ secrets.CONTABO_SERVER_SSH_KEY }} > thexci

    - name: Copy Docker Compose file
      run: scp -i thexci hub/docker-compose.yml ${{ secrets.CONTABO_SERVER_USER }}@${{ secrets.CONTABO_SERVER_IP }}:/home/thexci

    - name: Run the Service
      run: ssh -i thexci ${{ secrets.CONTABO_SERVER_USER }}@${{ secrets.CONTABO_SERVER_IP }} -t "docker compose up -d"
