name: FE Service CI

on:
  push:
    branches:
      - main
    paths:
      - ./hub/fe

  pull_request:
    branches:
      - main
    paths:
      - ./hub/fe

jobs:
  buildnpush:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image (FE)
      run: docker build ./hub/fe --tag jawadc/thex:fe-latest

    - name: Push Docker image (FE)
      run: docker push jawadc/thex:fe-latest
